beanstalkd:
  host: 10.98.134.148
  port: 11300
  tubes:
    annotation:
      submission: annotation
      events: annotation_events
    saveFromQuery:
      submission: saveFromQuery
      events: saveFromQuery_events
    index:
      submission: index
      events: index_events
    filters:
      submission: filters
      events: filters_events
  events:
    started: started
    completed: completed
    failed: failed
    progress: progress
database_dir: /mnt/annotator/beanstalk/index
temp_dir: /mnt/annotator/tmp/
