assembly: dm3
build_author: ec2-user
build_date: 2018-05-28T02:47:00
chromosomes:
  - chr2L
  - chr2LHet
  - chr2R
  - chr2RHet
  - chr3L
  - chr3LHet
  - chr3R
  - chr3RHet
  - chr4
  - chrM
  - chrU
  - chrUextra
  - chrX
  - chrXHet
  - chrYHet
database_dir: "~"
files_dir: "~"
statistics:
  dbSNPnameField: ""
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tsv
    tab: .statistics.tsv
  refTrackField: ref
  siteTypeField: refSeq.siteType
fileProcessors:
  snp:
    args: --emptyField ! --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField ! --keepId --keepPos
    program: bystro-vcf
temp_dir: ~
tracks:
  - build_author: ec2-user
    build_date: 2018-05-20T13:51:00
    fetch_date: 2018-05-20T13:41:00
    local_files:
      - chr2LHet.fa
      - chr2R.fa
      - chr2RHet.fa
      - chr3L.fa
      - chr3LHet.fa
      - chr3R.fa
      - chr3RHet.fa
      - chr4.fa
      - chrM.fa
      - chrU.fa
      - chrUextra.fa
      - chrX.fa
      - chrXHet.fa
      - chrYHet.fa
      - chr2L.fa
    name: ref
    remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/dm3/bigZips/
    remote_files:
      - chromFa.tar.gz
    type: reference
    version: 1
  - build_author: ec2-user
    build_date: 2018-05-20T13:51:00
    features:
      - name
      - name2
    fetch_date: 2018-05-20T13:43:00
    local_files:
      - dm3.refGene.chr2L.gz
      - dm3.refGene.chr2LHet.gz
      - dm3.refGene.chr2R.gz
      - dm3.refGene.chr2RHet.gz
      - dm3.refGene.chr3L.gz
      - dm3.refGene.chr3LHet.gz
      - dm3.refGene.chr3R.gz
      - dm3.refGene.chr3RHet.gz
      - dm3.refGene.chr4.gz
      - dm3.refGene.chrU.gz
      - dm3.refGene.chrUextra.gz
      - dm3.refGene.chrX.gz
      - dm3.refGene.chrXHet.gz
      - dm3.refGene.chrYHet.gz
    name: refSeq
    nearest:
      - name
      - name2
    sql_statement: SELECT * FROM dm3.refGene
    type: gene
    version: 1
  - build_author: ec2-user
    build_date: 2018-05-28T02:47:00
    features:
      - name
      - name2
    fetch_date: 2018-05-28T02:40:00
    local_files:
      - dm3.ensGene.chr2L.gz
      - dm3.ensGene.chr2LHet.gz
      - dm3.ensGene.chr2R.gz
      - dm3.ensGene.chr2RHet.gz
      - dm3.ensGene.chr3L.gz
      - dm3.ensGene.chr3LHet.gz
      - dm3.ensGene.chr3R.gz
      - dm3.ensGene.chr3RHet.gz
      - dm3.ensGene.chr4.gz
      - dm3.ensGene.chrM.gz
      - dm3.ensGene.chrU.gz
      - dm3.ensGene.chrUextra.gz
      - dm3.ensGene.chrX.gz
      - dm3.ensGene.chrXHet.gz
      - dm3.ensGene.chrYHet.gz
    name: ensGene
    nearest:
      - name
      - name2
    sql_statement: SELECT * FROM dm3.ensGene
    type: gene
    version: 2
  - build_author: ec2-user
    build_date: 2018-05-20T13:51:00
    fetch_date: 2018-05-20T13:47:00
    local_files:
      - chr2LHet.pp
      - chr2R.pp
      - chr2RHet.pp
      - chr3L.pp
      - chr3LHet.pp
      - chr3R.pp
      - chr3RHet.pp
      - chr4.pp
      - chrM.pp
      - chrU.pp
      - chrUextra.pp
      - chrX.pp
      - chrXHet.pp
      - chrYHet.pp
      - chr2L.pp
    name: phastCons
    remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/dm3/phastCons15way/
    remote_files:
      - chr2LHet.pp
      - chr2R.pp
      - chr2RHet.pp
      - chr3L.pp
      - chr3LHet.pp
      - chr3R.pp
      - chr3RHet.pp
      - chr4.pp
      - chrM.pp
      - chrU.pp
      - chrUextra.pp
      - chrX.pp
      - chrXHet.pp
      - chrYHet.pp
      - chr2L.pp
    type: score
    version: 1
version: 2
