---
assembly: hg19
build_author: ec2-user
build_date: 2018-02-26T22:21:00
chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrM
  - chrX
  - chrY
database_dir: ~
files_dir: ~
fileProcessors:
  snp:
    args: --emptyField ! --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField ! --sample %sampleList% --keepPos
    program: bystro-vcf
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tsv
    tab: .statistics.tsv
  programPath: bystro-stats
  refTrackField: ref
  siteTypeField: refSeq.siteType
temp_dir: ~
tracks:
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    fetch_date: 2017-02-04T22:36:00
    local_files:
      - chr*.fa.gz
    name: ref
    remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
    remote_files:
      - chr1.fa.gz
      - chr2.fa.gz
      - chr3.fa.gz
      - chr4.fa.gz
      - chr5.fa.gz
      - chr6.fa.gz
      - chr7.fa.gz
      - chr8.fa.gz
      - chr9.fa.gz
      - chr10.fa.gz
      - chr11.fa.gz
      - chr12.fa.gz
      - chr13.fa.gz
      - chr14.fa.gz
      - chr15.fa.gz
      - chr16.fa.gz
      - chr17.fa.gz
      - chr18.fa.gz
      - chr19.fa.gz
      - chr20.fa.gz
      - chr21.fa.gz
      - chr22.fa.gz
      - chrM.fa.gz
      - chrX.fa.gz
      - chrY.fa.gz
    type: reference
    version: 6
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    features:
      - kgID
      - mRNA
      - spID
      - spDisplayID
      - protAcc
      - description
      - rfamAcc
      - name
      - name2
    fetch_date: 2018-02-26T21:53:00
    join:
      features:
        - alleleID
        - phenotypeList
        - clinicalSignificance
        - type
        - origin
        - numberSubmitters
        - reviewStatus
        - chromStart
        - chromEnd
      track: clinvar
    local_files:
      - hg19.refGene.chr1.gz
      - hg19.refGene.chr2.gz
      - hg19.refGene.chr3.gz
      - hg19.refGene.chr4.gz
      - hg19.refGene.chr5.gz
      - hg19.refGene.chr6.gz
      - hg19.refGene.chr7.gz
      - hg19.refGene.chr8.gz
      - hg19.refGene.chr9.gz
      - hg19.refGene.chr10.gz
      - hg19.refGene.chr11.gz
      - hg19.refGene.chr12.gz
      - hg19.refGene.chr13.gz
      - hg19.refGene.chr14.gz
      - hg19.refGene.chr15.gz
      - hg19.refGene.chr16.gz
      - hg19.refGene.chr17.gz
      - hg19.refGene.chr18.gz
      - hg19.refGene.chr19.gz
      - hg19.refGene.chr20.gz
      - hg19.refGene.chr21.gz
      - hg19.refGene.chr22.gz
      - hg19.refGene.chrM.gz
      - hg19.refGene.chrX.gz
      - hg19.refGene.chrY.gz
    name: refSeq
    nearest:
      - name
      - name2
    sql_statement:
      SELECT * FROM hg19.refGene LEFT JOIN hg19.kgXref ON hg19.kgXref.refseq
      = hg19.refGene.name
    type: gene
    version: 6
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    fetch_date: 2017-02-04T16:52:00
    local_files:
      - chr*.phastCons100way.wigFix.gz
    name: phastCons
    remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
    remote_files:
      - chr1.phastCons100way.wigFix.gz
      - chr2.phastCons100way.wigFix.gz
      - chr3.phastCons100way.wigFix.gz
      - chr4.phastCons100way.wigFix.gz
      - chr5.phastCons100way.wigFix.gz
      - chr6.phastCons100way.wigFix.gz
      - chr7.phastCons100way.wigFix.gz
      - chr8.phastCons100way.wigFix.gz
      - chr9.phastCons100way.wigFix.gz
      - chr10.phastCons100way.wigFix.gz
      - chr11.phastCons100way.wigFix.gz
      - chr12.phastCons100way.wigFix.gz
      - chr13.phastCons100way.wigFix.gz
      - chr14.phastCons100way.wigFix.gz
      - chr15.phastCons100way.wigFix.gz
      - chr16.phastCons100way.wigFix.gz
      - chr17.phastCons100way.wigFix.gz
      - chr18.phastCons100way.wigFix.gz
      - chr19.phastCons100way.wigFix.gz
      - chr20.phastCons100way.wigFix.gz
      - chr21.phastCons100way.wigFix.gz
      - chr22.phastCons100way.wigFix.gz
      - chrX.phastCons100way.wigFix.gz
      - chrY.phastCons100way.wigFix.gz
      - chrM.phastCons100way.wigFix.gz
    type: score
    version: 6
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    fetch_date: 2017-02-03T20:57:00
    local_files:
      - chr*.phyloP100way.wigFix.gz
    name: phyloP
    remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
    remote_files:
      - chr1.phyloP100way.wigFix.gz
      - chr2.phyloP100way.wigFix.gz
      - chr3.phyloP100way.wigFix.gz
      - chr4.phyloP100way.wigFix.gz
      - chr5.phyloP100way.wigFix.gz
      - chr6.phyloP100way.wigFix.gz
      - chr7.phyloP100way.wigFix.gz
      - chr8.phyloP100way.wigFix.gz
      - chr9.phyloP100way.wigFix.gz
      - chr10.phyloP100way.wigFix.gz
      - chr11.phyloP100way.wigFix.gz
      - chr12.phyloP100way.wigFix.gz
      - chr13.phyloP100way.wigFix.gz
      - chr14.phyloP100way.wigFix.gz
      - chr15.phyloP100way.wigFix.gz
      - chr16.phyloP100way.wigFix.gz
      - chr17.phyloP100way.wigFix.gz
      - chr18.phyloP100way.wigFix.gz
      - chr19.phyloP100way.wigFix.gz
      - chr20.phyloP100way.wigFix.gz
      - chr21.phyloP100way.wigFix.gz
      - chr22.phyloP100way.wigFix.gz
      - chrX.phyloP100way.wigFix.gz
      - chrY.phyloP100way.wigFix.gz
      - chrM.phyloP100way.wigFix.gz
    type: score
    version: 6
  - build_author: ec2-user
    caddToBed_date: 2018-09-07T00:00:00
    remote_files:
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr1.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr2.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr3.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr4.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr5.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr6.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr7.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr8.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr9.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr10.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr11.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr12.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr13.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr14.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr15.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr16.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr17.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr18.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr19.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr20.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr21.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chr22.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chrX.organized-by-chr.txt.sorted.txt.gz
      - s3://bystro-db/src/cadd1.4/hg38/cadd/whole_genome_SNVs.tsv.chrY.organized-by-chr.txt.sorted.txt.gz
    name: cadd
    sortCadd_date: 2018-09-07T00:00:00
    sorted_guaranteed: 1
    type: cadd
    version: 6
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    build_field_transformations:
      alleleFreqs: split [,]
      alleleNs: split [,]
      alleles: split [,]
      func: split [,]
      observed: split [\/]
    features:
      - name
      - strand
      - observed
      - class
      - func
      - alleles
      - alleleNs: number
      - alleleFreqs: number
    fetch_date: 2017-02-04T21:35:00
    name: dbSNP
    sql_statement: SELECT * FROM hg19.snp151
    type: sparse
    version: 6
  - based: 1
    build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    build_field_transformations:
      chrom: chr .
      clinicalSignificance: split [;]
      origin: split [;]
      phenotypeList: split [;]
      reviewStatus: split [;]
      type: split [;]
    build_row_filters:
      Assembly: == GRCh37
    features:
      - alleleID: number
      - phenotypeList
      - clinicalSignificance
      - type
      - origin
      - numberSubmitters: number
      - reviewStatus
      - referenceAllele
      - alternateAllele
    fetch_date: 2018-02-26T21:56:00
    fieldMap:
      "#AlleleID": alleleID
      AlternateAllele: alternateAllele
      Chromosome: chrom
      ClinicalSignificance: clinicalSignificance
      NumberSubmitters: numberSubmitters
      Origin: origin
      PhenotypeIDS: phenotypeIDs
      PhenotypeList: phenotypeList
      ReferenceAllele: referenceAllele
      ReviewStatus: reviewStatus
      Start: chromStart
      Stop: chromEnd
      Type: type
    local_files:
      - variant_summary.txt.gz
    name: clinvar
    remote_files:
      - ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
    type: sparse
    version: 6
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    build_row_filters:
      AS_FilterStatus: == PASS
    features:
      - alt
      - id
      - af: number
      - an: number
      - an_afr: number
      - an_amr: number
      - an_asj: number
      - an_eas: number
      - an_fin: number
      - an_nfe: number
      - an_oth: number
      - an_male: number
      - an_female: number
      - af_afr: number
      - af_amr: number
      - af_asj: number
      - af_eas: number
      - af_fin: number
      - af_nfe: number
      - af_oth: number
      - af_male: number
      - af_female: number
    fieldMap:
      AF: af
      AF_AFR: af_afr
      AF_AMR: af_amr
      AF_ASJ: af_asj
      AF_EAS: af_eas
      AF_FIN: af_fin
      AF_Female: af_female
      AF_Male: af_male
      AF_NFE: af_nfe
      AF_OTH: af_oth
      AF_SAS: af_sas
      AN: an
      AN_AFR: an_afr
      AN_AMR: an_amr
      AN_ASJ: an_asj
      AN_EAS: an_eas
      AN_FIN: an_fin
      AN_Female: an_female
      AN_Male: an_male
      AN_NFE: an_nfe
      AN_OTH: an_oth
      AN_SAS: an_sas
    remote_files:
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.1.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.2.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.3.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.4.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.5.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.6.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.7.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.8.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.9.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.10.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.11.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.12.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.13.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.14.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.15.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.16.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.17.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.18.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.19.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.20.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.21.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.22.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.X.vcf.bgz
    name: gnomad.genomes
    type: vcf
    version: 6
  - build_author: ec2-user
    build_date: 2018-01-17T20:32:00
    build_row_filters:
      AS_FilterStatus: == PASS
    features:
      - alt
      - id
      - af: number
      - an: number
      - an_afr: number
      - an_amr: number
      - an_asj: number
      - an_eas: number
      - an_fin: number
      - an_nfe: number
      - an_oth: number
      - an_sas: number
      - an_male: number
      - an_female: number
      - af_afr: number
      - af_amr: number
      - af_asj: number
      - af_eas: number
      - af_fin: number
      - af_nfe: number
      - af_oth: number
      - af_sas: number
      - af_male: number
      - af_female: number
    fieldMap:
      AF: af
      AF_AFR: af_afr
      AF_AMR: af_amr
      AF_ASJ: af_asj
      AF_EAS: af_eas
      AF_FIN: af_fin
      AF_Female: af_female
      AF_Male: af_male
      AF_NFE: af_nfe
      AF_OTH: af_oth
      AF_SAS: af_sas
      AN: an
      AN_AFR: an_afr
      AN_AMR: an_amr
      AN_ASJ: an_asj
      AN_EAS: an_eas
      AN_FIN: an_fin
      AN_Female: an_female
      AN_Male: an_male
      AN_NFE: an_nfe
      AN_OTH: an_oth
      AN_SAS: an_sas
    remote_files:
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.1.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.2.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.3.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.4.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.5.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.6.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.7.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.8.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.9.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.10.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.11.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.12.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.13.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.14.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.15.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.16.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.17.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.18.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.19.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.20.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.21.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.22.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.X.vcf.bgz
      - https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.Y.vcf.bgz
    name: gnomad.exomes
    type: vcf
    version: 6
version: 11
