---
assembly: hg19
build_author: ec2-user
build_date: 2018-01-14T16:21:00
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: '~'
fileProcessors:
  snp:
    args: --emptyField ! --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField !
    program: bystro-vcf
files: '~'
files_dir: /mnt/db_backup/hg19/
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tsv
    tab: .statistics.tsv
  programPath: bystro-stats
  refTrackField: ref
  siteTypeField: refSeq.siteType
temp_dir: '~'
tracks:
  outputOrder:
  - ref
  - refSeq
  - refSeq.gene
  - nearest.refSeq
  - nearestTss.refSeq
  - phastCons
  - phyloP
  - cadd
  - gnomad.genomes
  - gnomad.exomes
  - dbSNP
  - clinvar
  tracks:
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    local_files:
    - chr*.fa.gz
    name: ref
    type: reference
    utils:
    - args:
        remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
        remoteFiles:
        - chr1.fa.gz
        - chr2.fa.gz
        - chr3.fa.gz
        - chr4.fa.gz
        - chr5.fa.gz
        - chr6.fa.gz
        - chr7.fa.gz
        - chr8.fa.gz
        - chr9.fa.gz
        - chr10.fa.gz
        - chr11.fa.gz
        - chr12.fa.gz
        - chr13.fa.gz
        - chr14.fa.gz
        - chr15.fa.gz
        - chr16.fa.gz
        - chr17.fa.gz
        - chr18.fa.gz
        - chr19.fa.gz
        - chr20.fa.gz
        - chr21.fa.gz
        - chr22.fa.gz
        - chrM.fa.gz
        - chrX.fa.gz
        - chrY.fa.gz
      completed: 2017-11-24T02:27:00
      name: fetch
    version: 23
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    dist: true
    features:
    - name2
    - name
    from: txStart
    local_files:
    - hg19.kgXref.chr*.with_dbnsfp.gz
    name: nearest.refSeq
    to: txEnd
    type: nearest
    utils:
    - args:
        renameTo: nearest.refSeq
      completed: 2017-12-24T20:10:00
      name: renameTrack
    version: 14
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    dist: true
    features:
    - name2
    - name
    from: txStart
    local_files:
    - hg19.kgXref.chr*.with_dbnsfp.gz
    name: nearestTss.refSeq
    type: nearest
    utils:
    - args:
        renameTo: nearestTss.refSeq
      completed: 2017-12-24T20:10:00
      name: renameTrack
    version: 14
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    local_files:
    - chr*.phastCons100way.wigFix.gz
    name: phastCons
    type: score
    utils:
    - args:
        remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
        remoteFiles:
        - chr1.phastCons100way.wigFix.gz
        - chr2.phastCons100way.wigFix.gz
        - chr3.phastCons100way.wigFix.gz
        - chr4.phastCons100way.wigFix.gz
        - chr5.phastCons100way.wigFix.gz
        - chr6.phastCons100way.wigFix.gz
        - chr7.phastCons100way.wigFix.gz
        - chr8.phastCons100way.wigFix.gz
        - chr9.phastCons100way.wigFix.gz
        - chr10.phastCons100way.wigFix.gz
        - chr11.phastCons100way.wigFix.gz
        - chr12.phastCons100way.wigFix.gz
        - chr13.phastCons100way.wigFix.gz
        - chr14.phastCons100way.wigFix.gz
        - chr15.phastCons100way.wigFix.gz
        - chr16.phastCons100way.wigFix.gz
        - chr17.phastCons100way.wigFix.gz
        - chr18.phastCons100way.wigFix.gz
        - chr19.phastCons100way.wigFix.gz
        - chr20.phastCons100way.wigFix.gz
        - chr21.phastCons100way.wigFix.gz
        - chr22.phastCons100way.wigFix.gz
        - chrX.phastCons100way.wigFix.gz
        - chrY.phastCons100way.wigFix.gz
        - chrM.phastCons100way.wigFix.gz
      completed: 2017-11-23T21:05:00
      name: fetch
    version: 15
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    local_files:
    - chr*.phyloP100way.wigFix.gz
    name: phyloP
    type: score
    utils:
    - args:
        remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
        remoteFiles:
        - chr1.phyloP100way.wigFix.gz
        - chr2.phyloP100way.wigFix.gz
        - chr3.phyloP100way.wigFix.gz
        - chr4.phyloP100way.wigFix.gz
        - chr5.phyloP100way.wigFix.gz
        - chr6.phyloP100way.wigFix.gz
        - chr7.phyloP100way.wigFix.gz
        - chr8.phyloP100way.wigFix.gz
        - chr9.phyloP100way.wigFix.gz
        - chr10.phyloP100way.wigFix.gz
        - chr11.phyloP100way.wigFix.gz
        - chr12.phyloP100way.wigFix.gz
        - chr13.phyloP100way.wigFix.gz
        - chr14.phyloP100way.wigFix.gz
        - chr15.phyloP100way.wigFix.gz
        - chr16.phyloP100way.wigFix.gz
        - chr17.phyloP100way.wigFix.gz
        - chr18.phyloP100way.wigFix.gz
        - chr19.phyloP100way.wigFix.gz
        - chr20.phyloP100way.wigFix.gz
        - chr21.phyloP100way.wigFix.gz
        - chr22.phyloP100way.wigFix.gz
        - chrX.phyloP100way.wigFix.gz
        - chrY.phyloP100way.wigFix.gz
        - chrM.phyloP100way.wigFix.gz
      completed: 2017-11-23T21:10:00
      name: fetch
    version: 14
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    caddToBed_date: 2017-04-22T06:41:00
    liftOverCadd_date: 2017-07-28T17:35:00
    local_files:
    - whole_genome_SNVs.tsv.bed.chr*.organized-by-chr.txt.sorted.txt.gz
    - whole_genome_SNVs.tsv.bed.chrM.organized-by-chr.txt.sorted.txt.mapped.gz
    name: cadd
    sortCadd_date: 2017-04-23T15:44:00
    sort_date: 2017-01-20T16:06:00
    sorted_guaranteed: 1
    type: cadd
    version: 14
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    build_field_transformations:
      description: split [;]
      ensemblID: split [;]
      kgID: split [;]
      mRNA: split [;]
      protAcc: split [;]
      rfamAcc: split [;]
      spDisplayID: split [;]
      spID: split [;]
      tRnaName: split [;]
    features:
    - name
    - name2
    - description
    - kgID
    - mRNA
    - spID
    - spDisplayID
    - protAcc
    - rfamAcc
    - tRnaName
    - ensemblID
    join:
      features:
      - alleleID
      - phenotypeList
      - clinicalSignificance
      - type
      - origin
      - numberSubmitters
      - reviewStatus
      - chromStart
      - chromEnd
      track: clinvar
    local_files:
    - hg19.kgXref.chr*.with_dbnsfp.gz
    name: refSeq
    type: gene
    utils:
    - args:
        connection:
          database: hg19
        sql: SELECT r.*, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.kgID, '')) SEPARATOR
          ';') FROM kgXref x WHERE x.refseq=r.name) AS kgID, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.description,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS description,
          (SELECT GROUP_CONCAT(DISTINCT(NULLIF(e.value, '')) SEPARATOR ';') FROM knownToEnsembl
          e JOIN kgXref x ON x.kgID = e.name WHERE x.refseq = r.name) AS ensemblID,
          (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.tRnaName, '')) SEPARATOR ';') FROM
          kgXref x WHERE x.refseq=r.name) AS tRnaName, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.spID,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS spID, (SELECT
          GROUP_CONCAT(DISTINCT(NULLIF(x.spDisplayID, '')) SEPARATOR ';') FROM kgXref
          x WHERE x.refseq=r.name) AS spDisplayID, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.protAcc,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS protAcc, (SELECT
          GROUP_CONCAT(DISTINCT(NULLIF(x.mRNA, '')) SEPARATOR ';') FROM kgXref x WHERE
          x.refseq=r.name) AS mRNA, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.rfamAcc,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS rfamAcc FROM
          refGene r WHERE chrom=%chromosomes%;
      completed: 2017-12-26T21:35:00
      name: fetch
    - args:
        geneFile: /mnt/db_backup/dbnsfp/dbNSFP3.5_gene.complete
      completed: 2017-12-26T21:46:00
      name: refGeneXdbnsfp
    version: 23
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    build_field_transformations:
      pmid: split [;]
      uniprot.func: split [;]
    dist: false
    features:
    - name2
    - pLi: number
    - pRec: number
    - pNull: number
    - lofTool: number
    - lofFdr: number
    - pHi: number
    - nonTCGA.pRec: number
    - nonTCGA.pNull: number
    - nonTCGA.pLi: number
    - nonPsych.pRec: number
    - nonPsych.pNull: number
    - nonPsych.pLi: number
    - gdi: number
    - cnvScore: number
    - cnvFlag
    - pmid: number
    - rvis: number
    fieldMap:
      dbnsfp.Disease_description: uniprot.disease
      dbnsfp.ExAC_cnv.score: cnvScore
      dbnsfp.ExAC_cnv_flag: cnvFlag
      dbnsfp.ExAC_nonTCGA_pLI: nonTCGA.pLi
      dbnsfp.ExAC_nonTCGA_pNull: nonTCGA.pNull
      dbnsfp.ExAC_nonTCGA_pRec: nonTCGA.pRec
      dbnsfp.ExAC_nonpsych_pLI: nonPsych.pLi
      dbnsfp.ExAC_nonpsych_pNull: nonPsych.pNull
      dbnsfp.ExAC_nonpsych_pRec: nonPsych.pRec
      dbnsfp.ExAC_pLI: pLi
      dbnsfp.ExAC_pNull: pNull
      dbnsfp.ExAC_pRec: pRec
      dbnsfp.Expression(GNF/Atlas): gnfAtlas.expression
      dbnsfp.Expression(egenetics): egenetics.expression
      dbnsfp.Function_description: uniprot.func
      dbnsfp.GDI-Phred: gdi
      dbnsfp.GO_biological_process: go.biologicalProcess
      dbnsfp.GO_cellular_component: go.cellularComponent
      dbnsfp.GO_molecular_function: go.molecularFunction
      dbnsfp.Known_rec_info: knownRecInfo
      dbnsfp.LoF-FDR_ExAC: lofFdr
      dbnsfp.LoFtool_score: lofTool
      dbnsfp.P(HI): pHi
      dbnsfp.P(rec): pRec
      dbnsfp.RVIS_percentile_ExAC: rvis
      dbnsfp.Tissue_specificity(Uniprot): uniprot.tissue
      dbnsfp.Trait_association(GWAS): gwasTraitAssoc
      dbnsfp.pubmedID: pmid
    from: txStart
    local_files:
    - hg19.kgXref.chr*.with_dbnsfp.gz
    name: refSeq.gene
    storeNearest: false
    to: txEnd
    type: nearest
    version: 19
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    build_field_transformations:
      alleleFreqs: split [,]
      alleleNs: split [,]
      alleles: split [,]
      func: split [,]
      observed: split [\/]
    features:
    - name
    - strand
    - observed
    - class
    - func
    - alleles
    - alleleNs: number
    - alleleFreqs: number
    local_files:
    - hg19.snp150.chr*.gz
    name: dbSNP
    type: sparse
    utils:
    - args:
        sql: SELECT * FROM hg19.snp150 WHERE chrom = %chromosomes%
      completed: 2017-11-24T03:23:00
      name: fetch
    version: 23
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    build_row_filters:
      AS_FilterStatus: == PASS
    features:
    - alt
    - id
    - af: number
    - an: number
    - an_afr: number
    - an_amr: number
    - an_asj: number
    - an_eas: number
    - an_fin: number
    - an_nfe: number
    - an_oth: number
    - an_sas: number
    - an_male: number
    - an_female: number
    - af_afr: number
    - af_amr: number
    - af_asj: number
    - af_eas: number
    - af_fin: number
    - af_nfe: number
    - af_oth: number
    - af_sas: number
    - af_male: number
    - af_female: number
    fieldMap:
      AF: af
      AF_AFR: af_afr
      AF_AMR: af_amr
      AF_ASJ: af_asj
      AF_EAS: af_eas
      AF_FIN: af_fin
      AF_Female: af_female
      AF_Male: af_male
      AF_NFE: af_nfe
      AF_OTH: af_oth
      AF_SAS: af_sas
      AN: an
      AN_AFR: an_afr
      AN_AMR: an_amr
      AN_ASJ: an_asj
      AN_EAS: an_eas
      AN_FIN: an_fin
      AN_Female: an_female
      AN_Male: an_male
      AN_NFE: an_nfe
      AN_OTH: an_oth
      AN_SAS: an_sas
    local_files:
    - gnomad.genomes.r2.0.2.sites.chr*.vcf.bgz
    name: gnomad.genomes
    type: vcf
    version: 17
  - build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    build_row_filters:
      AS_FilterStatus: == PASS
    features:
    - alt
    - id
    - af: number
    - an: number
    - an_afr: number
    - an_amr: number
    - an_asj: number
    - an_eas: number
    - an_fin: number
    - an_nfe: number
    - an_oth: number
    - an_sas: number
    - an_male: number
    - an_female: number
    - af_afr: number
    - af_amr: number
    - af_asj: number
    - af_eas: number
    - af_fin: number
    - af_nfe: number
    - af_oth: number
    - af_sas: number
    - af_male: number
    - af_female: number
    fieldMap:
      AF: af
      AF_AFR: af_afr
      AF_AMR: af_amr
      AF_ASJ: af_asj
      AF_EAS: af_eas
      AF_FIN: af_fin
      AF_Female: af_female
      AF_Male: af_male
      AF_NFE: af_nfe
      AF_OTH: af_oth
      AF_SAS: af_sas
      AN: an
      AN_AFR: an_afr
      AN_AMR: an_amr
      AN_ASJ: an_asj
      AN_EAS: an_eas
      AN_FIN: an_fin
      AN_Female: an_female
      AN_Male: an_male
      AN_NFE: an_nfe
      AN_OTH: an_oth
      AN_SAS: an_sas
    local_files:
    - gnomad.exomes.r2.0.2.sites.vcf.bgz
    name: gnomad.exomes
    type: vcf
    version: 17
  - based: 1
    build_author: ec2-user
    build_date: 2018-01-14T16:21:00
    build_field_transformations:
      chrom: chr .
      clinicalSignificance: split [;]
      origin: split [;]
      phenotypeList: split [;]
      reviewStatus: split [;]
      type: split [;]
    build_row_filters:
      Assembly: == GRCh37
    features:
    - alleleID: number
    - phenotypeList
    - clinicalSignificance
    - type
    - origin
    - numberSubmitters: number
    - reviewStatus
    - referenceAllele
    - alternateAllele
    fieldMap:
      '#AlleleID': alleleID
      AlternateAllele: alternateAllele
      Chromosome: chrom
      ClinicalSignificance: clinicalSignificance
      NumberSubmitters: numberSubmitters
      Origin: origin
      PhenotypeIDS: phenotypeIDs
      PhenotypeList: phenotypeList
      ReferenceAllele: referenceAllele
      ReviewStatus: reviewStatus
      Start: chromStart
      Stop: chromEnd
      Type: type
    local_files:
    - variant_summary.txt.gz
    name: clinvar
    type: sparse
    utils:
    - args:
        remoteFiles:
        - ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
      completed: 2017-11-23T21:04:00
      name: fetch
    version: 14
version: 208

