---
assembly: hg19
build_author: ec2-user
build_date: 2017-11-27T05:44:00
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: ~
files_dir: ~
snpProcessor: bystro-snp
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tsv
    tab: .statistics.tsv
  programPath: bystro-stats
  refTrackField: ref
  siteTypeField: refSeq.siteType
temp_dir: ~
tracks:
- build_author: ec2-user
  build_date: 2017-11-27T05:44:00
  local_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chr20.fa.gz
  - chr21.fa.gz
  - chr22.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  name: ref
  type: reference
  utils:
  - args:
      remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
      remoteFiles:
      - chr1.fa.gz
      - chr2.fa.gz
      - chr3.fa.gz
      - chr4.fa.gz
      - chr5.fa.gz
      - chr6.fa.gz
      - chr7.fa.gz
      - chr8.fa.gz
      - chr9.fa.gz
      - chr10.fa.gz
      - chr11.fa.gz
      - chr12.fa.gz
      - chr13.fa.gz
      - chr14.fa.gz
      - chr15.fa.gz
      - chr16.fa.gz
      - chr17.fa.gz
      - chr18.fa.gz
      - chr19.fa.gz
      - chr20.fa.gz
      - chr21.fa.gz
      - chr22.fa.gz
      - chrM.fa.gz
      - chrX.fa.gz
      - chrY.fa.gz
    completed: 2017-11-24T02:27:00
    name: fetch
  version: 9
- build_author: ec2-user
  features:
  - kgID
  - mRNA
  - spID
  - spDisplayID
  - protAcc
  - description
  - rfamAcc
  - name
  - name2
  join:
    features:
    - alleleID
    - phenotypeList
    - clinicalSignificance
    - type
    - origin
    - numberSubmitters
    - reviewStatus
    - chromStart
    - chromEnd
    track: clinvar
  local_files:
  - hg19.refGene.chr4.with_dbnsfp.gz
  - hg19.refGene.chr8.with_dbnsfp.gz
  - hg19.refGene.chr5.with_dbnsfp.gz
  - hg19.refGene.chr3.with_dbnsfp.gz
  - hg19.refGene.chr6.with_dbnsfp.gz
  - hg19.refGene.chr1.with_dbnsfp.gz
  - hg19.refGene.chr7.with_dbnsfp.gz
  - hg19.refGene.chr2.with_dbnsfp.gz
  - hg19.refGene.chr9.with_dbnsfp.gz
  - hg19.refGene.chr13.with_dbnsfp.gz
  - hg19.refGene.chr10.with_dbnsfp.gz
  - hg19.refGene.chr12.with_dbnsfp.gz
  - hg19.refGene.chr11.with_dbnsfp.gz
  - hg19.refGene.chr15.with_dbnsfp.gz
  - hg19.refGene.chr14.with_dbnsfp.gz
  - hg19.refGene.chr16.with_dbnsfp.gz
  - hg19.refGene.chr18.with_dbnsfp.gz
  - hg19.refGene.chr17.with_dbnsfp.gz
  - hg19.refGene.chrX.with_dbnsfp.gz
  - hg19.refGene.chr20.with_dbnsfp.gz
  - hg19.refGene.chrM.with_dbnsfp.gz
  - hg19.refGene.chr19.with_dbnsfp.gz
  - hg19.refGene.chr22.with_dbnsfp.gz
  - hg19.refGene.chr21.with_dbnsfp.gz
  - hg19.refGene.chrY.with_dbnsfp.gz
  name: refSeq
  type: gene
  utils:
  - args:
      connection:
        database: hg19
      sql: SELECT r.name, chrom, strand, txStart, txEnd, cdsStart, cdsEnd, exonCount,
        exonStarts, exonEnds, score, name2, kgID, mRNA, spID, spDisplayID, refseq,
        protAcc, description, rfamAcc, tRnaName, value AS 'ensemblID', geneSymbol
        FROM refGene r LEFT JOIN kgXref k ON r.name = k.refseq LEFT JOIN knownToEnsembl
        e ON k.kgID = e.name WHERE chrom = %chromosomes%;
    completed: 2017-11-26T05:18:00
    name: fetch
  - args:
      geneFile: dbNSFP3.5_gene.complete
    completed: 2017-11-26T05:20:00
    name: refGeneXdbnsfp
  version: 3
- dist: true
  features:
  - name
  - name2
  from: txStart
  name: refSeq.nearest
  ref: refSeq
  to: txEnd
  type: nearest
- build_author: ec2-user
  build_date: 2017-11-27T05:44:00
  dist: true
  features:
  - name
  - name2
  from: txStart
  name: refSeq.nearestTss
  ref: refSeq
  type: nearest
  version: 3
- build_author: ec2-user
  build_date: 2017-04-21T05:08:00
  local_files:
  - chr1.phastCons100way.wigFix.gz
  - chr2.phastCons100way.wigFix.gz
  - chr3.phastCons100way.wigFix.gz
  - chr4.phastCons100way.wigFix.gz
  - chr5.phastCons100way.wigFix.gz
  - chr6.phastCons100way.wigFix.gz
  - chr7.phastCons100way.wigFix.gz
  - chr8.phastCons100way.wigFix.gz
  - chr9.phastCons100way.wigFix.gz
  - chr10.phastCons100way.wigFix.gz
  - chr11.phastCons100way.wigFix.gz
  - chr12.phastCons100way.wigFix.gz
  - chr13.phastCons100way.wigFix.gz
  - chr14.phastCons100way.wigFix.gz
  - chr15.phastCons100way.wigFix.gz
  - chr16.phastCons100way.wigFix.gz
  - chr17.phastCons100way.wigFix.gz
  - chr18.phastCons100way.wigFix.gz
  - chr19.phastCons100way.wigFix.gz
  - chr20.phastCons100way.wigFix.gz
  - chr21.phastCons100way.wigFix.gz
  - chr22.phastCons100way.wigFix.gz
  - chrX.phastCons100way.wigFix.gz
  - chrY.phastCons100way.wigFix.gz
  - chrM.phastCons100way.wigFix.gz
  name: phastCons
  type: score
  utils:
  - args:
      remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
      remoteFiles:
      - chr1.phastCons100way.wigFix.gz
      - chr2.phastCons100way.wigFix.gz
      - chr3.phastCons100way.wigFix.gz
      - chr4.phastCons100way.wigFix.gz
      - chr5.phastCons100way.wigFix.gz
      - chr6.phastCons100way.wigFix.gz
      - chr7.phastCons100way.wigFix.gz
      - chr8.phastCons100way.wigFix.gz
      - chr9.phastCons100way.wigFix.gz
      - chr10.phastCons100way.wigFix.gz
      - chr11.phastCons100way.wigFix.gz
      - chr12.phastCons100way.wigFix.gz
      - chr13.phastCons100way.wigFix.gz
      - chr14.phastCons100way.wigFix.gz
      - chr15.phastCons100way.wigFix.gz
      - chr16.phastCons100way.wigFix.gz
      - chr17.phastCons100way.wigFix.gz
      - chr18.phastCons100way.wigFix.gz
      - chr19.phastCons100way.wigFix.gz
      - chr20.phastCons100way.wigFix.gz
      - chr21.phastCons100way.wigFix.gz
      - chr22.phastCons100way.wigFix.gz
      - chrX.phastCons100way.wigFix.gz
      - chrY.phastCons100way.wigFix.gz
      - chrM.phastCons100way.wigFix.gz
    completed: 2017-11-23T21:05:00
    name: fetch
  version: 3
- build_author: ec2-user
  build_date: 2017-04-21T05:08:00
  local_files:
  - chr1.phyloP100way.wigFix.gz
  - chr2.phyloP100way.wigFix.gz
  - chr3.phyloP100way.wigFix.gz
  - chr4.phyloP100way.wigFix.gz
  - chr5.phyloP100way.wigFix.gz
  - chr6.phyloP100way.wigFix.gz
  - chr7.phyloP100way.wigFix.gz
  - chr8.phyloP100way.wigFix.gz
  - chr9.phyloP100way.wigFix.gz
  - chr10.phyloP100way.wigFix.gz
  - chr11.phyloP100way.wigFix.gz
  - chr12.phyloP100way.wigFix.gz
  - chr13.phyloP100way.wigFix.gz
  - chr14.phyloP100way.wigFix.gz
  - chr15.phyloP100way.wigFix.gz
  - chr16.phyloP100way.wigFix.gz
  - chr17.phyloP100way.wigFix.gz
  - chr18.phyloP100way.wigFix.gz
  - chr19.phyloP100way.wigFix.gz
  - chr20.phyloP100way.wigFix.gz
  - chr21.phyloP100way.wigFix.gz
  - chr22.phyloP100way.wigFix.gz
  - chrX.phyloP100way.wigFix.gz
  - chrY.phyloP100way.wigFix.gz
  - chrM.phyloP100way.wigFix.gz
  name: phyloP
  type: score
  utils:
  - args:
      remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
      remoteFiles:
      - chr1.phyloP100way.wigFix.gz
      - chr2.phyloP100way.wigFix.gz
      - chr3.phyloP100way.wigFix.gz
      - chr4.phyloP100way.wigFix.gz
      - chr5.phyloP100way.wigFix.gz
      - chr6.phyloP100way.wigFix.gz
      - chr7.phyloP100way.wigFix.gz
      - chr8.phyloP100way.wigFix.gz
      - chr9.phyloP100way.wigFix.gz
      - chr10.phyloP100way.wigFix.gz
      - chr11.phyloP100way.wigFix.gz
      - chr12.phyloP100way.wigFix.gz
      - chr13.phyloP100way.wigFix.gz
      - chr14.phyloP100way.wigFix.gz
      - chr15.phyloP100way.wigFix.gz
      - chr16.phyloP100way.wigFix.gz
      - chr17.phyloP100way.wigFix.gz
      - chr18.phyloP100way.wigFix.gz
      - chr19.phyloP100way.wigFix.gz
      - chr20.phyloP100way.wigFix.gz
      - chr21.phyloP100way.wigFix.gz
      - chr22.phyloP100way.wigFix.gz
      - chrX.phyloP100way.wigFix.gz
      - chrY.phyloP100way.wigFix.gz
      - chrM.phyloP100way.wigFix.gz
    completed: 2017-11-23T21:10:00
    name: fetch
  version: 3
- build_author: ec2-user
  build_date: 2017-04-21T05:08:00
  caddToBed_date: 2017-04-22T06:41:00
  liftOverCadd_date: 2017-07-28T17:35:00
  local_files:
  - whole_genome_SNVs.tsv.bed.chr*.organized-by-chr.txt.sorted.txt.gz
  - whole_genome_SNVs.tsv.bed.chrM.organized-by-chr.txt.sorted.txt.mapped.gz
  name: cadd
  sortCadd_date: 2017-04-23T15:44:00
  sort_date: 2017-01-20T16:06:00
  sorted_guaranteed: 1
  type: cadd
  version: 3
- build_author: ec2-user
  build_date: 2017-04-21T05:08:00
  build_field_transformations:
    alleleFreqs: split [,]
    alleleNs: split [,]
    alleles: split [,]
    func: split [,]
    observed: split [\/]
  features:
  - name
  - strand
  - observed
  - class
  - func
  - alleles
  - alleleNs: number
  - alleleFreqs: number
  local_files:
  - hg19.snp150.chr1.gz
  - hg19.snp150.chr2.gz
  - hg19.snp150.chr3.gz
  - hg19.snp150.chr4.gz
  - hg19.snp150.chr5.gz
  - hg19.snp150.chr6.gz
  - hg19.snp150.chr7.gz
  - hg19.snp150.chr8.gz
  - hg19.snp150.chr9.gz
  - hg19.snp150.chr10.gz
  - hg19.snp150.chr11.gz
  - hg19.snp150.chr12.gz
  - hg19.snp150.chr13.gz
  - hg19.snp150.chr14.gz
  - hg19.snp150.chr15.gz
  - hg19.snp150.chr16.gz
  - hg19.snp150.chr17.gz
  - hg19.snp150.chr18.gz
  - hg19.snp150.chr19.gz
  - hg19.snp150.chr20.gz
  - hg19.snp150.chr21.gz
  - hg19.snp150.chr22.gz
  - hg19.snp150.chrM.gz
  - hg19.snp150.chrX.gz
  - hg19.snp150.chrY.gz
  name: dbSNP
  type: sparse
  utils:
  - args:
      sql: SELECT * FROM hg19.snp150 WHERE chrom = %chromosomes%
    completed: 2017-11-24T03:23:00
    name: fetch
  version: 3
- build_author: ec2-user
  build_date: 2017-08-31T06:00:00
  build_row_filters:
    AS_FilterStatus: == PASS
  features:
  - alt
  - id
  - af: number
  - an: number
  - an_afr: number
  - an_amr: number
  - an_asj: number
  - an_eas: number
  - an_fin: number
  - an_nfe: number
  - an_oth: number
  - an_male: number
  - an_female: number
  - af_afr: number
  - af_amr: number
  - af_asj: number
  - af_eas: number
  - af_fin: number
  - af_nfe: number
  - af_oth: number
  - af_male: number
  - af_female: number
  fieldMap:
    AF: af
    AF_AFR: af_afr
    AF_AMR: af_amr
    AF_ASJ: af_asj
    AF_EAS: af_eas
    AF_FIN: af_fin
    AF_Female: af_female
    AF_Male: af_male
    AF_NFE: af_nfe
    AF_OTH: af_oth
    AN: an
    AN_AFR: an_afr
    AN_AMR: an_amr
    AN_ASJ: an_asj
    AN_EAS: an_eas
    AN_FIN: an_fin
    AN_Female: an_female
    AN_Male: an_male
    AN_NFE: an_nfe
    AN_OTH: an_oth
  local_files:
  - gnomad.genomes.r2.0.1.sites.*.vcf.gz
  name: gnomad.genomes
  type: vcf
  version: 1
- build_author: ec2-user
  build_date: 2017-08-31T06:00:00
  build_row_filters:
    AS_FilterStatus: == PASS
  features:
  - alt
  - id
  - af: number
  - an: number
  - an_afr: number
  - an_amr: number
  - an_asj: number
  - an_eas: number
  - an_fin: number
  - an_nfe: number
  - an_oth: number
  - an_male: number
  - an_female: number
  - af_afr: number
  - af_amr: number
  - af_asj: number
  - af_eas: number
  - af_fin: number
  - af_nfe: number
  - af_oth: number
  - af_male: number
  - af_female: number
  fieldMap:
    AF: af
    AF_AFR: af_afr
    AF_AMR: af_amr
    AF_ASJ: af_asj
    AF_EAS: af_eas
    AF_FIN: af_fin
    AF_Female: af_female
    AF_Male: af_male
    AF_NFE: af_nfe
    AF_OTH: af_oth
    AN: an
    AN_AFR: an_afr
    AN_AMR: an_amr
    AN_ASJ: an_asj
    AN_EAS: an_eas
    AN_FIN: an_fin
    AN_Female: an_female
    AN_Male: an_male
    AN_NFE: an_nfe
    AN_OTH: an_oth
  local_files:
  - gnomad.exomes.r2.0.1.sites.vcf.gz
  name: gnomad.exomes
  type: vcf
  version: 1
- based: 1
  build_author: ec2-user
  build_date: 2017-04-21T05:08:00
  build_field_transformations:
    chrom: chr .
    clinicalSignificance: split [;]
    origin: split [;]
    phenotypeList: split [;]
    reviewStatus: split [;]
    type: split [;]
  build_row_filters:
    Assembly: == GRCh37
  features:
  - alleleID: number
  - phenotypeList
  - clinicalSignificance
  - type
  - origin
  - numberSubmitters: number
  - reviewStatus
  - referenceAllele
  - alternateAllele
  fieldMap:
    '#AlleleID': alleleID
    AlternateAllele: alternateAllele
    Chromosome: chrom
    ClinicalSignificance: clinicalSignificance
    NumberSubmitters: numberSubmitters
    PhenotypeIDS: phenotypeIDs
    PhenotypeList: phenotypeList
    ReferenceAllele: referenceAllele
    ReviewStatus: reviewStatus
    Start: chromStart
    Stop: chromEnd
    Type: type
  local_files:
  - variant_summary.txt.gz
  name: clinvar
  type: sparse
  utils:
  - args:
      remoteFiles:
      - ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
    completed: 2017-11-23T21:04:00
    name: fetch
  version: 3
vcfProcessor: bystro-vcf
version: 158

